# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/334594289"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/fzwSSH"

[social.params]
icon = "brand-github"

[[social]]
identifier = "X"
name = "X"
url = "https://x.com/fourieding"

[social.params]
icon = "brand-twitter"
